apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: api
  name: api-service
spec:
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8081
      nodePort: 30100
  selector:
    io.kompose.service: api
  type: NodePort
