apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: api
  name: api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      io.kompose.service: api
  template:
    metadata:
      labels:
        io.kompose.service: api
    spec:
      containers:
        - image: brandaotaua/message-generator-api:v2
          name: api
          env:
            - name: spring.config.import
              value: optional:configserver:http://config-server:8888/
          ports:
            - containerPort: 8081