apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: brandaotaua/message-generator-api:v2
          ports:
            - containerPort: 8081
          env:
            - name: spring.config.import
              value: optional:configserver:http://config-server:8888/

---

apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30100